---
site_name: Awesome BIDS
repo_url: https://github.com/bids-standard/awesome-bids.git

nav:
-   Home: index.md
-   Contributing: contributing.md
-   Code of conduct: code-of-conduct.md

theme:
    name: material
    features:
    -   navigation.top
    -   content.action.edit
    icon:
        repo: fontawesome/brands/github
        edit: material/pencil
    palette:
    # Palette toggle for automatic mode
    -   media: (prefers-color-scheme)
        toggle:
            icon: material/brightness-auto
            name: Switch to light mode
    # Palette toggle for light mode
    -   media: '(prefers-color-scheme: light)'
        scheme: default
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
    # Palette toggle for dark mode
    -   media: '(prefers-color-scheme: dark)'
        scheme: slate
        toggle:
            icon: material/brightness-4
            name: Switch to system preference

edit_uri: edit/main/src/

markdown_extensions:
-   toc:
        anchorlink: true
-   pymdownx.superfences

plugins:
-   search

docs_dir: src

use_directory_urls: false
