---
name: Check Markdown links

on:
    push:
        branches: [main]
    pull_request:
        branches: '*'

jobs:
    markdown-link-check:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@master
        -   uses: tcort/github-action-markdown-link-check@v1
            with:
                use-quiet-mode: yes
                use-verbose-mode: yes
                folder-path: src
                config-file: md_link_check_config.json
